In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np
import cv2
import os
import random
import matplotlib.pyplot as plt
import pickle

In [4]:
DIRECTORY = '/content/drive/MyDrive/DataSet/train'
CATEGORIES = ['Five', 'One', 'Ten', 'Two']

In [5]:
data = []

for category in CATEGORIES:
  folder = os.path.join(DIRECTORY, category)
  label = CATEGORIES.index(category)
  for img in os.listdir(folder):
    img_path = os.path.join(folder,img)
    img_array = cv2.imread(img_path)
    data.append([img_array, label])

In [6]:
len(data)

1421

In [7]:
random.shuffle(data)

In [8]:
data[0]

[array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  

In [9]:
X = []
y = []

for features, labels in data:
  X.append(features)
  y.append(labels)

In [10]:
X = np.array(X)
y = np.array(y)

In [11]:

len(y)

1421

In [12]:
pickle.dump(X,open('X.pkl','wb'))
pickle.dump(y,open('y.pkl','wb'))

In [13]:
X=pickle.load(open('X.pkl','rb'))
y = pickle.load(open('y.pkl','rb'))


In [14]:
X

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [15]:
y

array([3, 0, 0, ..., 3, 0, 0])

In [16]:
X = X/255

In [17]:
X

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        ...,

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 

In [18]:
X.shape

(1421, 200, 200, 3)

In [19]:
from tensorflow.keras.utils import to_categorical

In [20]:
y = to_categorical(y,10)

In [21]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

In [31]:
model = Sequential()

model.add(Conv2D(filters = 64, kernel_size = (3,3),input_shape = (200,200,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))



model.add(Conv2D(128, kernel_size = (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Dropout(0.5))
model.add(Flatten())

model.add(Dense(256,input_shape = (200,200,3), activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

In [32]:
import tensorflow as tf
opt = tf.keras.optimizers.RMSprop(
    learning_rate=0.001, rho=0.9, momentum=0.0, epsilon=1e-07, centered=False,
    name='RMSprop'
)
model.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [33]:
model.fit(X,y,epochs = 100, validation_split = 0.1, steps_per_epoch=10, batch_size = 32)

Epoch 1/100
10/10 [==============================] - 55s 5s/step - loss: 26.7914 - accuracy: 0.2500 - val_loss: 1.7192 - val_accuracy: 0.2098
Epoch 2/100
10/10 [==============================] - 47s 5s/step - loss: 2.3894 - accuracy: 0.2906 - val_loss: 1.5132 - val_accuracy: 0.3706
Epoch 3/100
10/10 [==============================] - 47s 5s/step - loss: 1.5106 - accuracy: 0.3031 - val_loss: 1.2588 - val_accuracy: 0.3776
Epoch 4/100
10/10 [==============================] - 47s 5s/step - loss: 1.3313 - accuracy: 0.3742 - val_loss: 1.1952 - val_accuracy: 0.4126
Epoch 5/100
10/10 [==============================] - 47s 5s/step - loss: 1.3131 - accuracy: 0.4000 - val_loss: 1.1104 - val_accuracy: 0.5175
Epoch 6/100
10/10 [==============================] - 47s 5s/step - loss: 1.1272 - accuracy: 0.5281 - val_loss: 1.9246 - val_accuracy: 0.3077
Epoch 7/100
10/10 [==============================] - 47s 5s/step - loss: 1.7188 - accuracy: 0.3906 - val_loss: 1.0015 - val_accuracy: 0.5175
Epoch 8/100


In [46]:
testImg = cv2.imread('/content/drive/MyDrive/test/11.jpg')

In [50]:
testImg = cv2.resize(testImg,(200,200))

In [51]:
model.predict(testImg)

ValueError: ignored

In [52]:

filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))

INFO:tensorflow:Assets written to: ram://8e873bf1-0a15-45cb-9212-bc3a60966dbd/assets
